export const BUTTON = {
  _BLANK: '',
  NUM_0: '0',
  NUM_1: '1',
  NUM_2: '2',
  NUM_3: '3',
  NUM_4: '4',
  NUM_5: '5',
  NUM_6: '6',
  NUM_7: '7',
  NUM_8: '8',
  NUM_9: '9',
  NUM_DOT: '.',
  OP_AC: 'AC',
  OP_DIVIDE: '÷',
  OP_MULTIPLY: '×',
  OP_MINUS: '-',
  OP_PLUS: '+',
  OP_EQUALS: '=',
}
